### ISSUE TITLE
How do you authenticate

### ISSUE THREAD

**Issue by vladinator1000** [ripplr-io/docr-docker-publish#6]
Hi there, I added this to my workflow, but it gets stuck at the login step, retries a few times and fails with `unauthorized`. How are you supposed to authenticate?
```
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: DigitalOcean Docker Image Publish
        uses: ripplr-io/docr-docker-publish@v1
        with:
          image_path: registry/container
```
